apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Values.name }}
spec:
  template:
    metadata:
      labels:
        provisioner: {{ .Values.name }}
        NodeGroupType: {{ .Values.name }}
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          {{- with .Values.capacityTypes }}
          values:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          {{- with .Values.instanceFamilies }}
          values:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - key: "karpenter.k8s.aws/instance-size"
          operator: In
          {{- with .Values.instanceSizes }}
          values:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - key: "kubernetes.io/arch"
          operator: In
          {{- with .Values.instanceArchitectures }}
          values:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .Values.name }}
      {{- with .Values.taints }}
      taints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 120s
  {{- with .Values.limits }}
  limits:
    {{- toYaml . | nindent 4 }}
  {{- end }}
