name: default
clusterName:
vpcName:
nodeRole:
instanceSizes: ["large", "xlarge", "2xlarge", "4xlarge", "8xlarge"]
instanceFamilies: ["t3a", "c5", "m5", "r5", "r6g"]
instanceArchitectures: ["amd64"]
capacityTypes: ["spot", "on-demand"]
taints: []
amiFamily: AL2023
labels: {}
limits: {}
